server {
    listen 80;
    server_name trizw.space;

    # 用于 Let's Encrypt 验证 (Renewal needs this)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 强制跳转 HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name trizw.space;
    client_max_body_size 50M; # Increase upload size limit to 50MB

    ssl_certificate /etc/letsencrypt/live/trizw.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/trizw.space/privkey.pem;

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 静态文件缓存
    location /static/ {
        alias /app/static/;
        expires 30d;
    }
}
